// Writes js/photos.js (size, author, licence, source per photo slot) from tools/photos/credits.json.
// Run after the photo workflow has committed new downloads: node rajasthan/tools/photos/build-photos.mjs
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../..');
const credits = JSON.parse(fs.readFileSync(path.join(ROOT, 'tools/photos/credits.json'), 'utf8'));
// Commons author fields are free text; tidy the few that read badly as a credit line.
const AUTHOR = {
  'culture-pichwai': 'Unknown artist, Rajasthan, 19th century',
  'kishangarh': 'Unknown artist, Kishangarh school (Minneapolis Institute of Art)',
  'fest-holi': 'judepics (Flickr)',
  'ramgarh-crater': 'NASA Earth Science and Remote Sensing Unit',
  'culture-miniature': 'Sahib Din',
};
const out = {};
for (const [slot, c] of Object.entries(credits).sort()) {
  if (!fs.existsSync(path.join(ROOT, `img/${slot}-1600.jpg`)) || !fs.existsSync(path.join(ROOT, `img/${slot}-800.jpg`))) continue;
  const author = c.author.replace(/^This Photo was taken by\s*/i, '').replace(/\(\s*talk\s*\)/gi, '').replace(/^\(WT-en\)\s*/, '').replace(/\s+/g, ' ').trim().slice(0, 80);
  out[slot] = { w: c.w, h: c.h, author: AUTHOR[slot] || author, license: c.license, licenseUrl: c.licenseUrl, source: c.source, title: c.title };
}
fs.writeFileSync(path.join(ROOT, 'js/photos.js'), `// Generated by tools/photos/build-photos.mjs from tools/photos/credits.json. Do not edit by hand.\n// All photos from Wikimedia Commons under CC0, public domain, CC BY or CC BY-SA, resized and bundled.\nwindow.RJ_PHOTOS = ${JSON.stringify(out, null, 1)};\n`);
console.log('wrote js/photos.js with', Object.keys(out).length, 'photos');
