// Generated by tools/photos/build-photos.mjs from tools/photos/credits.json. Do not edit by hand.
// All photos from Wikimedia Commons under CC0, public domain, CC BY or CC BY-SA, resized and bundled.
window.RJ_PHOTOS = {
 "ajmer-sharif": {
  "w": 1600,
  "h": 720,
  "author": "Pinakpani",
  "license": "CC BY 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Ajmer_Sharif,_Dargah_of_Mainuddin_Chisti_in_Ajmer,_Rajasthan_33.jpg",
  "title": "Ajmer Sharif, Dargah of Mainuddin Chisti in Ajmer, Rajasthan 33.jpg"
 },
 "amber-ceiling": {
  "w": 1200,
  "h": 1600,
  "author": "Pim58",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:A_3D_View_of_Two_Walls_and_the_Ceiling_in_the_Mirror_Palace_of_Amer_Fort.jpg",
  "title": "A 3D View of Two Walls and the Ceiling in the Mirror Palace of Amer Fort.jpg"
 },
 "amber-diwan-i-aam": {
  "w": 1600,
  "h": 1200,
  "author": "Roshanrajverma",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Diwan_E_Aam_Amer_Fort.jpg",
  "title": "Diwan E Aam Amer Fort.jpg"
 },
 "amber-fort": {
  "w": 1600,
  "h": 1085,
  "author": "APS Kondhera",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:A_bird_eye_view_of_Amer_Fort_Jaipur,_India.jpg",
  "title": "A bird eye view of Amer Fort Jaipur, India.jpg"
 },
 "amber-ganesh-pol": {
  "w": 1600,
  "h": 1200,
  "author": "Chainwit.",
  "license": "CC BY 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Amer_Fort_-_Ganesh_Pol_(2022)_-_img_01.jpg",
  "title": "Amer Fort - Ganesh Pol (2022) - img 01.jpg"
 },
 "amber-jai-mandir": {
  "w": 1600,
  "h": 1067,
  "author": "Adityaoberai",
  "license": "CC BY 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Sheesh_Mahal_at_Amer_Fort.jpg",
  "title": "Sheesh Mahal at Amer Fort.jpg"
 },
 "amber-jaleb-chowk": {
  "w": 1600,
  "h": 900,
  "author": "Saurav78",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Amer_fort_glance.jpg",
  "title": "Amer fort glance.jpg"
 },
 "amber-mirror-detail": {
  "w": 1200,
  "h": 1600,
  "author": "Pim58",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:A_Work_of_Art_in_the_Amer_Fort_Mirror_Palace.jpg",
  "title": "A Work of Art in the Amer Fort Mirror Palace.jpg"
 },
 "amber-mirror-vase": {
  "w": 1600,
  "h": 1067,
  "author": "Vyacheslav Argenberg",
  "license": "CC BY 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Embossed_silver_artwork_in_Sheesh_Mahal,_Amer_Fort,_India.jpg",
  "title": "Embossed silver artwork in Sheesh Mahal, Amer Fort, India.jpg"
 },
 "amber-sheesh-mahal": {
  "w": 1600,
  "h": 1257,
  "author": "Ronakshah1990",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Sheesh_Mahal,_Amer_Fort.jpg",
  "title": "Sheesh Mahal, Amer Fort.jpg"
 },
 "amber-zenana": {
  "w": 1600,
  "h": 1067,
  "author": "Vyacheslav Argenberg",
  "license": "CC BY 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Amer_Fort,_Inner_courtyard,_India.jpg",
  "title": "Amer Fort, Inner courtyard, India.jpg"
 },
 "bagore-ki-haveli": {
  "w": 1600,
  "h": 799,
  "author": "Jakub Hałun",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:20191207_Gangaur_Ghat_and_Bagore_Ki_Haveli,_Udaipur_1524_7266.jpg",
  "title": "20191207 Gangaur Ghat and Bagore Ki Haveli, Udaipur 1524 7266.jpg"
 },
 "banswara": {
  "w": 1600,
  "h": 1067,
  "author": "Devendra Trivedi",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Siva_Temple_-Arthuna_-Banswara_-Rajasthan_-IMG_002.jpg",
  "title": "Siva Temple -Arthuna -Banswara -Rajasthan -IMG 002.jpg"
 },
 "bhangarh": {
  "w": 1600,
  "h": 1200,
  "author": "Chainwit.",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Bhangarh_Fort_-_Royal_Palace_Bhangarh_(July_2022)_-_img_02.jpg",
  "title": "Bhangarh Fort - Royal Palace Bhangarh (July 2022) - img 02.jpg"
 },
 "blue-city": {
  "w": 1600,
  "h": 1200,
  "author": "Reema Jalihal",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Mehrangarh_Fort_and_the_Blue_City_at_dawn,_Jodhpur.jpg",
  "title": "Mehrangarh Fort and the Blue City at dawn, Jodhpur.jpg"
 },
 "bundi": {
  "w": 1600,
  "h": 1067,
  "author": "Daniel VILLAFRUELA",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Bundi-Taragarh_fort-Garh_Palace-20131016.jpg",
  "title": "Bundi-Taragarh fort-Garh Palace-20131016.jpg"
 },
 "chand-baori": {
  "w": 1600,
  "h": 1065,
  "author": "Adityavijayavargia",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Chand_Baori,_Abaneri.jpg",
  "title": "Chand Baori, Abaneri.jpg"
 },
 "chittorgarh": {
  "w": 1600,
  "h": 1083,
  "author": "Deepank Ranka",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Vijay_Stambh_Chittorgarh_Fort_8.jpg",
  "title": "Vijay Stambh Chittorgarh Fort 8.jpg"
 },
 "city-palace-jaipur": {
  "w": 1600,
  "h": 1067,
  "author": "Jan Bockaert",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "source": "https://commons.wikimedia.org/wiki/File:Chandra_Mahal,_City_Palace_Jaipur_(16696511226).jpg",
  "title": "Chandra Mahal, City Palace Jaipur (16696511226).jpg"
 },
 "city-palace-udaipur": {
  "w": 1600,
  "h": 910,
  "author": "Jakub Hałun",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:20191207_City_Palace,_Udaipur_1701_7325.jpg",
  "title": "20191207 City Palace, Udaipur 1701 7325.jpg"
 },
 "culture-bandhani": {
  "w": 1600,
  "h": 1143,
  "author": "Swapnil.Karambelkar",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Bandhani_pagadi_tie_and_dye_work_on_cloth,jaipur_rajasthan_India.jpg",
  "title": "Bandhani pagadi tie and dye work on cloth,jaipur rajasthan India.jpg"
 },
 "culture-block-print": {
  "w": 1600,
  "h": 1059,
  "author": "Ketayun, Katz",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Anokhi_Hand_Block.jpg",
  "title": "Anokhi Hand Block.jpg"
 },
 "culture-blue-pottery": {
  "w": 1600,
  "h": 762,
  "author": "Atcelsius",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Blue_pottery_from_Jaipur_2.jpg",
  "title": "Blue pottery from Jaipur 2.jpg"
 },
 "culture-ghoomar": {
  "w": 1600,
  "h": 1067,
  "author": "Aali Jain",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Ghoomar_dancers_(Rajasthan,_India,_2023).jpg",
  "title": "Ghoomar dancers (Rajasthan, India, 2023).jpg"
 },
 "culture-kalbelia": {
  "w": 1600,
  "h": 1067,
  "author": "Kenneth Lewis",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Kalbelia_Dance_01.jpg",
  "title": "Kalbelia Dance 01.jpg"
 },
 "culture-kathputli": {
  "w": 1600,
  "h": 1148,
  "author": "Ravikiran Rao",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Puppet_Show.jpg",
  "title": "Puppet Show.jpg"
 },
 "culture-manganiyar": {
  "w": 1600,
  "h": 1067,
  "author": "BOMBMAN",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "source": "https://commons.wikimedia.org/wiki/File:Manganiers_using_musical_instrument_on_2014.jpg",
  "title": "Manganiers using musical instrument on 2014.jpg"
 },
 "culture-miniature": {
  "w": 1600,
  "h": 940,
  "author": "Sahib Din",
  "license": "Public domain",
  "licenseUrl": "",
  "source": "https://commons.wikimedia.org/wiki/File:Battle_at_Lanka,_Ramayana,_Udaipur,_1649-53.jpg",
  "title": "Battle at Lanka, Ramayana, Udaipur, 1649-53.jpg"
 },
 "culture-pichwai": {
  "w": 1567,
  "h": 1600,
  "author": "Unknown artist, Rajasthan, 19th century",
  "license": "Public domain",
  "licenseUrl": "",
  "source": "https://commons.wikimedia.org/wiki/File:Rajasthan,_India_-_Festival_of_the_Cattle_(Gopashtami);_shrine_hanging_(pichhavai)_-_Google_Art_Project.jpg",
  "title": "Rajasthan, India - Festival of the Cattle (Gopashtami); shrine hanging (pichhavai) - Google Art Project.jpg"
 },
 "desert-np": {
  "w": 1600,
  "h": 851,
  "author": "SVKMBFLY",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:The_Great_Indian_Bustard_(Ardeotis_nigriceps).jpg",
  "title": "The Great Indian Bustard (Ardeotis nigriceps).jpg"
 },
 "fest-desert": {
  "w": 1600,
  "h": 1067,
  "author": "Aranya Bhadu",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:A_jumping_camel.jpg",
  "title": "A jumping camel.jpg"
 },
 "fest-diwali": {
  "w": 1600,
  "h": 1064,
  "author": "Marc Shandro from Calgary, Canada",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "source": "https://commons.wikimedia.org/wiki/File:Diwali_street_decorations_in_Jaipur.jpg",
  "title": "Diwali street decorations in Jaipur.jpg"
 },
 "fest-gangaur": {
  "w": 1600,
  "h": 1067,
  "author": "Nikhil Vyas",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Gangaur_procession_in_Kishangarh,_Rajasthan.jpg",
  "title": "Gangaur procession in Kishangarh, Rajasthan.jpg"
 },
 "fest-holi": {
  "w": 1600,
  "h": 1200,
  "author": "judepics (Flickr)",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "source": "https://commons.wikimedia.org/wiki/File:Gulal_clouds_as_children_play_Holi_at_Pushkar,_Rajasthan.jpg",
  "title": "Gulal clouds as children play Holi at Pushkar, Rajasthan.jpg"
 },
 "fest-kites": {
  "w": 1600,
  "h": 1200,
  "author": "pradeep kumar chatte…",
  "license": "CC BY 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Festival_of_kite_flying._-_panoramio_(1).jpg",
  "title": "Festival of kite flying. - panoramio (1).jpg"
 },
 "fest-teej": {
  "w": 1600,
  "h": 1200,
  "author": "pradeep kumar chatte…",
  "license": "CC BY 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Festival_of_teej_in_India._-_panoramio.jpg",
  "title": "Festival of teej in India. - panoramio.jpg"
 },
 "food-dal-baati": {
  "w": 1600,
  "h": 1326,
  "author": "Mahi Tatavarty",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:%22Delectable_Dal_Baati_Churma%22.jpg",
  "title": "\"Delectable Dal Baati Churma\".jpg"
 },
 "gadisar": {
  "w": 1600,
  "h": 1051,
  "author": "Clément Bardot",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Gadisar_Lake,_Jaisalmer.jpg",
  "title": "Gadisar Lake, Jaisalmer.jpg"
 },
 "gagron": {
  "w": 1600,
  "h": 1067,
  "author": "Siddharth 36",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Gagron_fort_submerged.jpg",
  "title": "Gagron fort submerged.jpg"
 },
 "hawa-mahal": {
  "w": 1600,
  "h": 1064,
  "author": "Jakub Hałun",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:20191218_Pa%C5%82ac_Wiatr%C3%B3w_w_Jaipurze_1129_9124.jpg",
  "title": "20191218 Pałac Wiatrów w Jaipurze 1129 9124.jpg"
 },
 "jaipur-walled-city": {
  "w": 1600,
  "h": 1063,
  "author": "Aleksandr Zykov from Russia",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "source": "https://commons.wikimedia.org/wiki/File:Pink_City,_Jaipur,_India_(21002921450).jpg",
  "title": "Pink City, Jaipur, India (21002921450).jpg"
 },
 "jaisalmer-fort": {
  "w": 1600,
  "h": 935,
  "author": "Clément Bardot",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Jaisalmer_Fort,_India.jpg",
  "title": "Jaisalmer Fort, India.jpg"
 },
 "jantar-mantar": {
  "w": 1600,
  "h": 979,
  "author": "Jakub Hałun",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Rashivilaya_Yantra,_Jantar_Mantar,_Jaipur,_20191218_0923_9016.jpg",
  "title": "Rashivilaya Yantra, Jantar Mantar, Jaipur, 20191218 0923 9016.jpg"
 },
 "jaswant-thada": {
  "w": 1600,
  "h": 1004,
  "author": "Clément Bardot",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Jaswant_Thada_cenotaph_2.jpg",
  "title": "Jaswant Thada cenotaph 2.jpg"
 },
 "jawai": {
  "w": 1600,
  "h": 1066,
  "author": "Tisha Mukherjee",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Indian_leopard_in_Jawai_Bandh_April_2025_by_Tisha_Mukherjee_06.jpg",
  "title": "Indian leopard in Jawai Bandh April 2025 by Tisha Mukherjee 06.jpg"
 },
 "junagarh": {
  "w": 1600,
  "h": 1064,
  "author": "Jakub Hałun",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:20191211_Junagarh_Fort,_Bikaner,_India_1547_8077_DxO.jpg",
  "title": "20191211 Junagarh Fort, Bikaner, India 1547 8077 DxO.jpg"
 },
 "karni-mata": {
  "w": 1600,
  "h": 1064,
  "author": "Jakub Hałun",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:20191212_%C5%9Awi%C4%85tynia_Karni_Maty_w_De%C5%9Bnok_1031_8078_DxO.jpg",
  "title": "20191212 Świątynia Karni Maty w Deśnok 1031 8078 DxO.jpg"
 },
 "keoladeo": {
  "w": 1600,
  "h": 1067,
  "author": "Giles Laurent",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:051_Chital_swimming_in_Keoladeo_National_Park_Photo_by_Giles_Laurent.jpg",
  "title": "051 Chital swimming in Keoladeo National Park Photo by Giles Laurent.jpg"
 },
 "khejarli": {
  "w": 1600,
  "h": 1200,
  "author": "Dinesh Valke from Thane, India",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "source": "https://commons.wikimedia.org/wiki/File:Prosopis_cineraria_(L.)_Druce_(45661098141).jpg",
  "title": "Prosopis cineraria (L.) Druce (45661098141).jpg"
 },
 "kishangarh": {
  "w": 1600,
  "h": 1030,
  "author": "Unknown artist, Kishangarh school (Minneapolis Institute of Art)",
  "license": "Public domain",
  "licenseUrl": "",
  "source": "https://commons.wikimedia.org/wiki/File:Unknown_artist,_India_-_Bani_Thani_Bathing_at_Pholl_Sagar_Palace_-_88.26.2_-_Minneapolis_Institute_of_Art.jpg",
  "title": "Unknown artist, India - Bani Thani Bathing at Pholl Sagar Palace - 88.26.2 - Minneapolis Institute of Art.jpg"
 },
 "kuldhara": {
  "w": 1600,
  "h": 1200,
  "author": "Archan dave",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Kuldhara.JPG",
  "title": "Kuldhara.JPG"
 },
 "kumbhalgarh": {
  "w": 1600,
  "h": 1200,
  "author": "Sutharmahaveer",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Longest_wall_in_india_of_kumbhalgarh_fort.jpg",
  "title": "Longest wall in india of kumbhalgarh fort.jpg"
 },
 "lake-pichola": {
  "w": 1600,
  "h": 1000,
  "author": "UnpetitproleX",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Lake_Pichola_at_sunset,_Udaipur,_Rajasthan,_India.jpg",
  "title": "Lake Pichola at sunset, Udaipur, Rajasthan, India.jpg"
 },
 "mandawa": {
  "w": 1600,
  "h": 1058,
  "author": "Clément Bardot",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Haveli,_Mandawa_3.jpg",
  "title": "Haveli, Mandawa 3.jpg"
 },
 "mehrangarh": {
  "w": 1600,
  "h": 1022,
  "author": "Yann",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Mehrangarh_Fort_2,_Jodhpur,_Rajasthan,_India.jpg",
  "title": "Mehrangarh Fort 2, Jodhpur, Rajasthan, India.jpg"
 },
 "mount-abu": {
  "w": 1600,
  "h": 1067,
  "author": "Sanyam Bahga",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Nakki_Lake,_Mount_Abu,_Rajasthan,_610.jpg",
  "title": "Nakki Lake, Mount Abu, Rajasthan, 610.jpg"
 },
 "nahargarh": {
  "w": 1600,
  "h": 1064,
  "author": "Jakub Hałun",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:20191218_Fort_Nahargarh,_Jaipur_1531_9318_DxO.jpg",
  "title": "20191218 Fort Nahargarh, Jaipur 1531 9318 DxO.jpg"
 },
 "nawalgarh": {
  "w": 1600,
  "h": 1200,
  "author": "Thérèse Gaigé",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Morarka_Haveli_Museum,_Nawalgarh_-_09.jpg",
  "title": "Morarka Haveli Museum, Nawalgarh - 09.jpg"
 },
 "osian": {
  "w": 1600,
  "h": 954,
  "author": "Schwiki",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Osiya-temple_and_Architecture_47.jpg",
  "title": "Osiya-temple and Architecture 47.jpg"
 },
 "patwon-ki-haveli": {
  "w": 1600,
  "h": 1200,
  "author": "Sreesarkar",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Patwon_ki_Haveli_Jaisalmer.jpg",
  "title": "Patwon ki Haveli Jaisalmer.jpg"
 },
 "pushkar": {
  "w": 1600,
  "h": 1064,
  "author": "Jakub Hałun",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:20191215_Jezioro_Puszkar_i_ghaty_na_p%C3%B3%C5%82nocno-wschodnim_brzegu_0932_8635.jpg",
  "title": "20191215 Jezioro Puszkar i ghaty na północno-wschodnim brzegu 0932 8635.jpg"
 },
 "pushkar-fair": {
  "w": 1600,
  "h": 1065,
  "author": "Chetansoni",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Old_tribe_Man.jpg",
  "title": "Old tribe Man.jpg"
 },
 "ramgarh-crater": {
  "w": 1600,
  "h": 1067,
  "author": "NASA Earth Science and Remote Sensing Unit",
  "license": "Public domain",
  "licenseUrl": "",
  "source": "https://commons.wikimedia.org/wiki/File:ISS061-E-139042_-_View_of_India.jpg",
  "title": "ISS061-E-139042 - View of India.jpg"
 },
 "ranakpur": {
  "w": 1600,
  "h": 978,
  "author": "Banerjeedebasis",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Pillars_of_Ranakpur_Jain_Temple_02.jpg",
  "title": "Pillars of Ranakpur Jain Temple 02.jpg"
 },
 "ranthambore": {
  "w": 1600,
  "h": 1067,
  "author": "Sujai.rajapaul",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:A_tiger_at_Ranthambore_National_Park_(2016)_6.jpg",
  "title": "A tiger at Ranthambore National Park (2016) 6.jpg"
 },
 "sam-dunes": {
  "w": 1600,
  "h": 1200,
  "author": "Roshanrajverma",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Sam_dunes_(Jaisalmer).jpg",
  "title": "Sam dunes (Jaisalmer).jpg"
 },
 "sambhar": {
  "w": 1600,
  "h": 1200,
  "author": "Nawanshu91",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Sambhar_lake.JPG",
  "title": "Sambhar lake.JPG"
 },
 "samrat-yantra": {
  "w": 1600,
  "h": 1071,
  "author": "Sujay25",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Vrihat_samrat_yantra,_JantarMantar,_Jaipur,_Rajasthan.jpg",
  "title": "Vrihat samrat yantra, JantarMantar, Jaipur, Rajasthan.jpg"
 },
 "sariska": {
  "w": 1600,
  "h": 1200,
  "author": "GAURAV BANSAL",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Sariska_Tiger_Reserve_Beauty.jpg",
  "title": "Sariska Tiger Reserve Beauty.jpg"
 },
 "tal-chhapar": {
  "w": 1600,
  "h": 1067,
  "author": "Tisha Mukherjee",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Blackbuck_in_Tal_Chhapar_Sanctuary_November_2025_by_Tisha_Mukherjee_04.jpg",
  "title": "Blackbuck in Tal Chhapar Sanctuary November 2025 by Tisha Mukherjee 04.jpg"
 },
 "umaid-bhawan": {
  "w": 1600,
  "h": 1190,
  "author": "Yann",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Umaid_Bhawan,_Jodhpur.jpg",
  "title": "Umaid Bhawan, Jodhpur.jpg"
 },
 "wild-camel": {
  "w": 1600,
  "h": 986,
  "author": "Clément Bardot",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Dromedary_in_Thar_desert.jpg",
  "title": "Dromedary in Thar desert.jpg"
 },
 "wild-sarus": {
  "w": 1600,
  "h": 1067,
  "author": "Giles Laurent",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:055_Sarus_cranes_in_Keoladeo_National_Park_Photo_by_Giles_Laurent.jpg",
  "title": "055 Sarus cranes in Keoladeo National Park Photo by Giles Laurent.jpg"
 }
};
