// Builds rajasthan/js/geo.js from Natural Earth (public domain).
//   world land 1:110m (world-atlas package) for the globe,
//   Rajasthan and its neighbours from ne_10m_admin_1_states_provinces,
//   rivers from ne_10m_rivers_lake_centerlines.
// Usage: NE_DIR=/path/with/geojson node rajasthan/tools/build-geo.mjs
// (download the two GeoJSON files from github.com/nvkelso/natural-earth-vector/tree/master/geojson)
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import * as topo from 'topojson-client';

const require = createRequire(import.meta.url);
const NE = process.env.NE_DIR;
if (!NE) throw new Error('Set NE_DIR to the folder holding the Natural Earth GeoJSON files');
const load = (f) => JSON.parse(fs.readFileSync(path.join(NE, f), 'utf8'));
const r = (d) => (n) => Math.round(n * 10 ** d) / 10 ** d;

// Douglas–Peucker on a ring of [lon, lat]
function simplify(pts, tol) {
  if (pts.length < 4) return pts;
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop(); let max = 0, idx = -1;
    const [x1, y1] = pts[a], [x2, y2] = pts[b], dx = x2 - x1, dy = y2 - y1, len = Math.hypot(dx, dy) || 1e-12;
    for (let i = a + 1; i < b; i++) {
      const d = Math.abs(dy * pts[i][0] - dx * pts[i][1] + x2 * y1 - y2 * x1) / len;
      if (d > max) { max = d; idx = i; }
    }
    if (max > tol) { keep[idx] = 1; stack.push([a, idx], [idx, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}
const simpGeom = (g, tol, d) => {
  const ring = (rg) => simplify(rg, tol).map(([x, y]) => [r(d)(x), r(d)(y)]);
  if (g.type === 'Polygon') return { type: 'Polygon', coordinates: g.coordinates.map(ring).filter((x) => x.length > 3) };
  if (g.type === 'MultiPolygon') return { type: 'MultiPolygon', coordinates: g.coordinates.map((p) => p.map(ring).filter((x) => x.length > 3)).filter((p) => p.length) };
  if (g.type === 'LineString') return { type: 'LineString', coordinates: ring(g.coordinates) };
  if (g.type === 'MultiLineString') return { type: 'MultiLineString', coordinates: g.coordinates.map(ring) };
  return g;
};

const admin = load('ne_10m_admin_1_states_provinces.geojson');
const raj = admin.features.find((f) => f.properties.iso_3166_2 === 'IN-RJ');
const NEIGH = { 'IN-GJ': 'Gujarat', 'IN-MP': 'Madhya Pradesh', 'IN-UP': 'Uttar Pradesh', 'IN-HR': 'Haryana', 'IN-PB': 'Punjab', 'IN-DL': 'Delhi', 'PK-SD': 'Sindh', 'PK-PB': 'Punjab' };
const neighbours = admin.features.filter((f) => NEIGH[f.properties.iso_3166_2]).map((f) => ({ name: NEIGH[f.properties.iso_3166_2], country: f.properties.admin, geometry: simpGeom(f.geometry, 0.03, 2) }));

const BB = [68.8, 22.6, 78.6, 30.6];
const inBB = ([x, y]) => x > BB[0] && x < BB[2] && y > BB[1] && y < BB[3];
const rivers = load('ne_10m_rivers_lake_centerlines.geojson').features
  .filter((f) => f.properties.featurecla?.includes('River') && ['Chambal', 'Banas', 'Mahi', 'Parbati', 'Yamuna', 'Sutlej', 'Indus'].includes(f.properties.name))
  .filter((f) => f.geometry && (f.geometry.type === 'MultiLineString' ? f.geometry.coordinates.flat() : f.geometry.coordinates).some(inBB))
  .map((f) => ({ name: f.properties.name || '', geometry: simpGeom(f.geometry, 0.01, 3) }));

const land = require('world-atlas/land-110m.json');
const landGeo = topo.feature(land, land.objects.land).features[0].geometry;
const round = (c, f) => (Array.isArray(c[0]) ? c.map((x) => round(x, f)) : c.map(f));
landGeo.coordinates = round(landGeo.coordinates, r(2));

const out = {
  source: 'Natural Earth 1:10m admin-1 and rivers, 1:110m land (public domain). Boundaries are approximate.',
  rajasthan: simpGeom(raj.geometry, 0.006, 3),
  neighbours, rivers, land: landGeo,
};
const file = new URL('../js/geo.js', import.meta.url);
fs.writeFileSync(file, `// Generated by tools/build-geo.mjs. ${out.source}\nwindow.RJ_GEO = ${JSON.stringify(out)};\n`);
console.log('wrote js/geo.js', (fs.statSync(file).size / 1024).toFixed(0), 'KB;', rivers.length, 'rivers:', [...new Set(rivers.map((x) => x.name))].join(', '));
