// Downloads one freely licensed landscape photo per place from Wikimedia Commons,
// saves it to src/assets/photos/, and regenerates src/data/photos.ts with full attribution.
// Usage: npm run photos [-- --force] [-- --only=slug,slug]
// Needs network access to commons.wikimedia.org and upload.wikimedia.org.
import fs from 'node:fs';
import path from 'node:path';

const API = 'https://commons.wikimedia.org/w/api.php';
const UA = 'IntoBhutan/1.0 (https://github.com/suramya12/Claude_Repo-1; static travel guide)';
const OK_LICENSE = /^(CC BY(-SA)? [0-9.]+|CC0|Public domain|PD)/i;
const terms = JSON.parse(fs.readFileSync('scripts/photo-sources.json', 'utf8'));
const manifestPath = 'scripts/photos.json';
const manifest = fs.existsSync(manifestPath) ? JSON.parse(fs.readFileSync(manifestPath, 'utf8')) : {};
const force = process.argv.includes('--force');
const only = (process.argv.find((a) => a.startsWith('--only=')) || '').slice(7).split(',').filter(Boolean);
const strip = (h = '') => h.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();

async function search(q) {
  const u = new URL(API);
  Object.entries({
    action: 'query', format: 'json', origin: '*', generator: 'search', gsrnamespace: '6', gsrlimit: '25',
    gsrsearch: `${q} filetype:bitmap`, prop: 'imageinfo', iiprop: 'url|size|extmetadata|mime', iiurlwidth: '2400',
  }).forEach(([k, v]) => u.searchParams.set(k, v));
  const r = await fetch(u, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`Commons API ${r.status}`);
  const j = await r.json();
  return Object.values(j.query?.pages ?? {}).sort((a, b) => a.index - b.index);
}

function pick(pages) {
  for (const p of pages) {
    const ii = p.imageinfo?.[0]; if (!ii) continue;
    const m = ii.extmetadata ?? {};
    const license = strip(m.LicenseShortName?.value);
    if (!OK_LICENSE.test(license)) continue;
    if (!/jpe?g/.test(ii.mime) || ii.width < 1600 || ii.width / ii.height < 1.2) continue;
    return {
      title: strip(m.ObjectName?.value) || p.title.replace(/^File:/, '').replace(/\.[a-z]+$/i, ''),
      author: strip(m.Artist?.value) || 'Unknown author',
      license,
      licenseUrl: m.LicenseUrl?.value || 'https://commons.wikimedia.org/wiki/Commons:Licensing',
      source: ii.descriptionurl,
      download: ii.thumburl || ii.url,
      alt: strip(m.ImageDescription?.value).slice(0, 160) || p.title.replace(/^File:/, ''),
    };
  }
  return null;
}

for (const [slug, q] of Object.entries(terms)) {
  if (slug.startsWith('_') || (only.length && !only.includes(slug))) continue;
  const file = `src/assets/photos/${slug}.jpg`;
  if (manifest[slug] && fs.existsSync(file) && !force) { console.log('keep', slug); continue; }
  try {
    const best = pick(await search(q));
    if (!best) { console.log('none', slug); continue; }
    const img = await fetch(best.download, { headers: { 'User-Agent': UA } });
    if (!img.ok) throw new Error(`download ${img.status}`);
    fs.writeFileSync(file, Buffer.from(await img.arrayBuffer()));
    const { download, ...meta } = best;
    manifest[slug] = meta;
    console.log('got ', slug, '·', meta.license, '·', meta.author);
  } catch (e) { console.log('fail', slug, e.message); }
  await new Promise((r) => setTimeout(r, 400));
}

fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
const slugs = Object.keys(manifest).filter((s) => fs.existsSync(`src/assets/photos/${s}.jpg`)).sort();
const id = (s) => 'p_' + s.replace(/-/g, '_');
const out = `// Generated by scripts/fetch-photos.mjs from scripts/photos.json. Do not edit by hand.
import type { ImageMetadata } from 'astro';
${slugs.map((s) => `import ${id(s)} from '../assets/photos/${s}.jpg';`).join('\n')}

/** Licensed photography, keyed by place slug. Any place without an entry falls back to its painted scene. */
export type Photo = { src: ImageMetadata; alt: string; author: string; license: string; licenseUrl: string; source: string; title: string };
export const PHOTOS: Record<string, Photo> = {
${slugs.map((s) => `  '${s}': { src: ${id(s)}, ...${JSON.stringify(manifest[s])} },`).join('\n')}
};
`;
fs.writeFileSync(path.join('src/data/photos.ts'), out);
console.log(`photos.ts: ${slugs.length} photos`);
