// Generated by scripts/fetch-photos.mjs from scripts/photos.json. Do not edit by hand.
import type { ImageMetadata } from 'astro';


/** Licensed photography, keyed by place slug. Any place without an entry falls back to its painted scene. */
export type Photo = { src: ImageMetadata; alt: string; author: string; license: string; licenseUrl: string; source: string; title: string };
export const PHOTOS: Record<string, Photo> = {

};
